spring.application.name=Lab7-Springboot
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.validate-on-migrate=false
spring.flyway.enabled=false